### ISSUE TITLE
Can't patch loop of type <class 'uvloop.Loop'>

### ISSUE THREAD

**Issue by zakcroft** [NVIDIA/NeMo-Guardrails#112]
Related imports into my app are set to
fastapi==0.96.0
uvicorn[standard]==0.22.0
openai==0.27.8
langchain==0.0.251
nemoguardrails==0.5.0

then 

from nemoguardrails import LLMRails, RailsConfig

Error:

File ".../open_ai.py", line 18, in <module>
    from nemoguardrails import LLMRails, RailsConfig
File ".../venv/lib/python3.11/site-packages/nemoguardrails/__init__.py", line 20, in <module>
    patch_asyncio.apply()
File ".../venv/lib/python3.11/site-packages/nemoguardrails/patch_asyncio.py", line 33, in apply
    nest_asyncio.apply()
File ".../venv/lib/python3.11/site-packages/nest_asyncio.py", line 19, in apply
    _patch_loop(loop)
File ".../venv/lib/python3.11/site-packages/nest_asyncio.py", line 175, in _patch_loop
    raise ValueError('Can\'t patch loop of type %s' % type(loop))
ValueError: Can't patch loop of type <class 'uvloop.Loop'>

Is this something to do with the latest changes with nest_asyncio?

**Comment by drazvan** [comment]
Yes, this is related to nest_asyncio. Only the asyncio loop is supported for patching. In your case, you should set the `DISABLE_NEST_ASYNCIO=True` environment variable so that the patching is not applied. 

https://github.com/NVIDIA/NeMo-Guardrails/blob/main/docs/user_guide/advanced/nested-async-loop.md 

I guess we can try to detect this automatically and not try to apply it if it's not asyncio. If you have a bit of time to contribute this, that would be hugely appreciated. 

Thanks!

**Comment by trebedea** [comment]
Seems like you can also specify to `unicorn` to use an `asyncio` loop: 
https://youtrack.jetbrains.com/issue/PY-57332

**Comment by zakcroft** [comment]
Thanks for your inputs. Both the above solutions work.

**Comment by lauradang** [comment]
Hi, I have the same setup (running guardrails with uvicorn). The above comments fix the issue at hand, but then I also get this issue: `RuntimeError: asyncio.run() cannot be called from a running event loop`. Any ideas?

**Comment by etburke** [comment]
@lauradang Try passing `--loop asyncio` to uvicorn without setting the environment variable. That works for me.
