### ISSUE TITLE
Is there a `.railsignore`?

### ISSUE THREAD

**Issue by Wildshire** [NVIDIA/NeMo-Guardrails#277]
Hello

Very quick question / topic. Is there a `.nemoignore` file to be added to the projects when loading `LLMRails` for example? Thing is, if I am doing some testing with colang files or a kb, sometimes I want to not load those files specifically. Only way I found to solve the issue is to delete files or folders. Perhaps there is another simpler workaround that I have not noticed yet.

Thanks in advance

**Comment by Wildshire** [comment]
Hello

I saw that in the last update to 0.8.0 you added these [configurations](https://github.com/NVIDIA/NeMo-Guardrails/blob/v0.8.0/docs/user_guides/advanced/generation-options.md#disabling-rails). This is a good step up into this issue.

Keep up the good work :)

PD: Leaving conversation open just in case something else is planned for the future

**Comment by drazvan** [comment]
Hi @Wildshire! Yes, that can be used. Also, #356 adds support for symlinks, so that could potentially be used as well. 
If you have a bit of time to contribute the support for a `.nemoignore`, I can guide you. Should not be a difficult one.

**Comment by Wildshire** [comment]
Hi @drazvan. Sorry for the late response. I might be able to help with this one. Where should I look into?

**Comment by drazvan** [comment]
First, let's call it `.railsingore`. I think the two main places where we want to apply the filtering are:
- https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/rails/llm/config.py#L469
- https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/nemoguardrails/actions/action_dispatcher.py#L300

You should create a helper function that we can invoke from various places. 
 
Thanks!

**Comment by ajanitshimanga** [comment]
Hi @drazvan! Yeah, I'd like to look into this issue as a first contribution! Some guidance would be greatly appreciated as I learn the codebase. Looking forward to tackling this!

**Comment by drazvan** [comment]
@ajanitshimanga : the discussion above should provide enough details. Let me know if you need additional guidance.

**Comment by ajanitshimanga** [comment]
Looking into this now 👍

**Comment by ajanitshimanga** [comment]
Hey @drazvan ,

Is it preferable for the filtering of `.co` files listed in `.railsignore` to take place on invocation of `_load_path` or in `_join_config` for `llm/config.py`?

Above you referenced `_join_config` in the first link and it seems to also be nicely handled near:

https://github.com/NVIDIA/NeMo-Guardrails/blob/5cbb2b63a509697b99adab9eaa4b9aa7c0a9c543/nemoguardrails/rails/llm/config.py#L583

where we can filter `.co` files that are found in `.railsignore` explicitly during loading rather than in config joining? I have started implementation as you described above in _join_config but wanted to ask on this.

Secondly, from your message above it seems that you would like the `ActionDispatcher`'s `_load_actions_from_module` to filter out `.py` modules based on the `.railsignore` as well. Is this correct? So essentially, end users will specify `.py` files and/or `.co` files in `.railsignore` to be filtered when we create `RailsConfig` or `ActionDispatcher`?

Thanks!

**Comment by Pouyanpi** [comment]
Hi @ajanitshimanga, 

Thanks for looking into this. Your approach looks good! 👍🏻

Having support for .py files would also be a nice addition. It would be great if you could add support for some glob patterns, similar to how .gitignore works, to filter out .co or .py files based on the pattern. If your design could be flexible enough to allow support for additional file types in the future, that would be ideal.

I suggest opening a PR so we can review it together and collaborate further if needed.

**Comment by ajanitshimanga** [comment]
Thanks @Pouyanpi , I’ll proceed with the information you’ve clarified. Thanks! I’ll open a PR soon after.

**Comment by ajanitshimanga** [comment]
Hi @Pouyanpi , I submitted a PR for the changes I've made. I would like to engage on what next steps would look like.

Thanks!
