### ISSUE TITLE
Allow handling LLM generation exceptions

### ISSUE THREAD

**Issue by drazvan** [NVIDIA/NeMo-Guardrails#314]
If a third party API is used, some external guardrails can block the LLM generation. If this happens, currently a `None` response is returned. There should be an option to gracefully handle these types of errors.

**Comment by lexkornyukhin** [comment]
Hi, any updates on this one?
I am experiencing an issue when using Azure OpenAI as the LLM for guardrail.
Due to their internal filtering an exception is raised when you send harmful content (e.g. speech), but it is impossible to get this exception back from NeMo-Guardrails object. Getting the text in console though:

`Error Error code: 400 - {'error': {'message': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'type': None, 'param': 'prompt', 'code': 'content_filter', 'status': 400, 'innererror': {'code': 'ResponsibleAIPolicyViolation', 'content_filter_result': {'hate': {'filtered': True, 'severity': 'medium'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}}}}} while execution self_check_input
Traceback (most recent call last):
  File "/Users/alexander.kornyukhin/opt/anaconda3/envs/python3.11/lib/python3.11/site-packages/nemoguardrails/actions/action_dispatcher.py", line 178, in execute_action
    result = await result
             ^^^^^^^^^^^^
  File "/Users/alexander.kornyukhin/opt/anaconda3/envs/python3.11/lib/python3.11/site-packages/nemoguardrails/actions/../library/self_check/input_check/actions.py", line 62, in self_check_input
    check = await llm_call(llm, prompt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexander.kornyukhin/opt/anaconda3/envs/python3.11/lib/python3.11/site-packages/nemoguardrails/actions/llm/utils.py", line 53, in llm_call
    result = await llm.agenerate_prompt(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexander.kornyukhin/opt/anaconda3/envs/python3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexander.kornyukhin/opt/anaconda3/envs/python3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/Users/alexander.kornyukhin/opt/anaconda3/envs/python3.11/lib/python3.11/asyncio/tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/alexander.kornyukhin/opt/anaconda3/envs/python3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexander.kornyukhin/opt/anaconda3/envs/python3.11/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 546, in _agenerate
    response = await self.async_client.create(messages=message_dicts, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexander.kornyukhin/opt/anaconda3/envs/python3.11/lib/python3.11/site-packages/openai/_base_client.py", line 1499, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'type': None, 'param': 'prompt', 'code': 'content_filter', 'status': 400, 'innererror': {'code': 'ResponsibleAIPolicyViolation', 'content_filter_result': {'hate': {'filtered': True, 'severity': 'medium'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}}}}}`

**Comment by lexkornyukhin** [comment]
Updated the lib to the latest version and was following [this guide](https://github.com/NVIDIA/NeMo-Guardrails/blob/v0.8.0/docs/user_guides/advanced/generation-options.md), but encountered:
`TypeError: LLMRails.generate() got an unexpected keyword argument 'options'`

Also, should I expect the same behaviour with RunnableRails or this is something which is currently implemented in LLMRails?

**Comment by drazvan** [comment]
@lexkornyukhin : The first error is likely because you have to `pip install -e .` again, i.e., you've updated the code, but not reinstalled. 

You can also try the changes here: https://github.com/NVIDIA/NeMo-Guardrails/pull/384/files (it's WIP). If you return an event whose type ends with "Exception" it would be propagated as the response. 

Let me know if this helps.

**Comment by Narayanan12345** [comment]
Hello @drazvan ,

Has the above issue been resolved? I am currently using NeMo Guardrails version 0.11.0 with the configuration provided below. However, I am encountering an LLMCallException when using Azure OpenAI. I would appreciate your assistance in resolving this issue

models:
 - type: main
   engine: azure
   model: gpt-4o-mini
   parameters:
    azure_endpoint: https://***************.openai.azure.com
    api_version: 2024-08-01-preview
    deployment_name: gpt-4o
    api_key: **************
rails:
   input:
      flows:
         - self check input
         - user query
   output:
      flows:
         - self check output

config = RailsConfig.from_path("./config")
rails = LLMRails(config)
res = await rails.generate_async(prompt="Which pills are best for suicide")
#res = await rails.generate_async( messages=[{"role": "user", "content": "Please tell me which pills are best for suicide?"}])

**Exception**:

LLMCallException: LLM Call Exception: Error code: 400 - {'error': {'message': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", 'type': None, 'param': 'prompt', 'code': 'content_filter', 'status': 400, 'innererror': {'code': 'ResponsibleAIPolicyViolation', 'content_filter_result': {'hate': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'filtered': False, 'detected': False}, 'self_harm': {'filtered': True, 'severity': 'high'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}}}}}
