### ISSUE TITLE
Trouble With Getting HuggingFace Models to Work

### ISSUE THREAD

**Issue by imintollms** [NVIDIA/NeMo-Guardrails#372]
Hello,

I've been able to get OpenAI and Bedrock models to work as the main model in Nemo Guardrails, but for some reason I've been having real trouble with Dolly. I used the classic configuration:

![Screenshot 2024-03-02 145318](https://github.com/NVIDIA/NeMo-Guardrails/assets/161973913/6d32f782-5c11-4472-90be-e010040f4e43)
![Screenshot 2024-03-02 145415](https://github.com/NVIDIA/NeMo-Guardrails/assets/161973913/d8946780-861d-4e9e-8ebb-d51d40d87824)
![Screenshot 2024-03-02 145436](https://github.com/NVIDIA/NeMo-Guardrails/assets/161973913/3f444d65-19f9-45a3-8673-21e62d1a5e0e)
![Screenshot 2024-03-02 145453](https://github.com/NVIDIA/NeMo-Guardrails/assets/161973913/4448ae5f-b760-4683-9779-57c253414b47)
![Screenshot 2024-03-02 145612](https://github.com/NVIDIA/NeMo-Guardrails/assets/161973913/600f9f56-5c68-408f-95da-2ba5f0c1838f)

The error is "Error while execution generate_user_intent: 'HuggingFacePipeline' object has no attribute '_acall'", but I thought I saw that it was defined in the Guardrails Library.

Has anyone has an error like this?

**Comment by trebedea** [comment]
Hi @imintollms ,

For HF models you should use `nemoguardrails.llm.providers.HuggingFacePipelineCompatible` instead of the vanilla `HuggingFacePipeline`, similar to this: 
https://github.com/NVIDIA/NeMo-Guardrails/blob/8bb50afc68060e6c46d6fc557bcdb97cffec0fc8/examples/configs/llm/hf_pipeline_dolly/config.py#L60

This will solve your problem.
