### ISSUE TITLE
Validation error while on Step 3 of Hello World - using gpt-3.5-turbo

### ISSUE THREAD

**Issue by UBGplus** [NVIDIA/NeMo-Guardrails#739]
ValidationError                           Traceback (most recent call last)
[<ipython-input-10-c5d5a703f1cd>](https://localhost:8080/#) in <cell line: 3>()
      1 from nemoguardrails import LLMRails
      2 
----> 3 rails = LLMRails(config)
      4 
      5 response = rails.generate(messages=[{

3 frames
[/usr/local/lib/python3.10/dist-packages/pydantic/v1/main.py](https://localhost:8080/#) in __init__(__pydantic_self__, **data)
    339         values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
    340         if validation_error:
--> 341             raise validation_error
    342         try:
    343             object_setattr(__pydantic_self__, '__dict__', values)

ValidationError: 1 validation error for ChatOpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter. (type=value_error)

**Comment by Pouyanpi** [comment]
Hi @UBGplus , have you set `OPENAI_API_KEY` as an environment variable?

**Comment by UBGplus** [comment]
This one is sorted now, i am able to run and test the Guardrails. Just need help with below. Can i launch Server and UI locally from Colab to test. If yes what are the exact steps.

!nemoguardrails server --config=.

INFO:     Started server process [27509]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

**Comment by trebedea** [comment]
From my experience, using something like `ngrok` is the simplest way to connect to a web server (including FastAPI / uvicorn) from Google Colab. It's pretty simple to use, see an example here: https://stackoverflow.com/a/63833779

**Comment by UBGplus** [comment]
Thank you for quick response, Can you guide me with steps Pls.

**Comment by Pouyanpi** [comment]
Hi @UBGplus , could you find a solution? 

So as mentioned by @trebedea, you have to run the server within the Colab environment and exposing it to the internet using a tunneling service like `ngrok`. 

Follow below steps:

### Install Packages


```python
!pip install nemoguardrails
!pip install pyngrok
```



###  Set Up ngrok

a. Sign Up for ngrok

 -  Go to [ngrok's website](https://ngrok.com/) and sign up for a free account 

 - After signing up, navigate to the [ngrok dashboard](https://dashboard.ngrok.com/get-started/your-authtoken) to find your authentication token.

b. Configure ngrok in Colab

Use the `pyngrok` library to set up ngrok with your authentication token

```python
from pyngrok import ngrok

# Replace 'YOUR_NGROK_AUTH_TOKEN' with the atcual token from your ngrok dashboard
ngrok.set_auth_token("YOUR_NGROK_AUTH_TOKEN")
```



### Start the Guardrails Server

Start the Guardrails server within Colab. Also run the server in the background so that the Colab notebook remains responsive.

```python
import subprocess
import time

server_process = subprocess.Popen(
    ["nemoguardrails", "server", "--config=."],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)

time.sleep(5)
```

> **Note:**
Ensure that your configuration file (e.g., `config.yaml`) exists in the current working directory of the Colab notebook.

### Expose the Server Using ngrok

Create an ngrok tunnel to make the guardrails server accessible via a public URL.

```python
public_url = ngrok.connect(8000)
print(f"Guardrails server is publicly accessible at: {public_url}")
```



### Try the Guardrails 

With the public URL provided by ngrok, you can now access the nemoguardrails server from your local machine's web browser:

Navigate to the URL printed by the previous step (e.g., `http://abcd1234.ngrok.io`) or simply post your requests to this url.

### Terminate the Server and ngrok Tunnel

After testing, it's goo to clean up by stopping the server and the ngrok tunnel.

```python
server_process.terminate()
ngrok.kill()
```

**Comment by Pouyanpi** [comment]
@manuelciosici, it is not really NeMo Guardrails related, but the above comment should resolve your issue, will close it for now.
