### ISSUE TITLE
Installation fails on windows 64-bit with 'ERROR: Could not build wheels for annoy, which is required to install pyproject.toml-based projects' error

### ISSUE THREAD

**Issue by archanadixit** [NVIDIA/NeMo-Guardrails#86]
Installation of nemoguardrails fails on windows 10 64-bit with 'ERROR: Could not build wheels for annoy, which is required to install pyproject.toml-based projects'. Here are more details about the env for reproducibility.

Python Env - Anaconda Distribution with Python 3.11.3 
OS - Windows 10 Enterprise 64-bit
Full Error -
===============
"""
pip install nemoguardrails
Collecting nemoguardrails
  Using cached nemoguardrails-0.3.0-py3-none-any.whl (13.8 MB)
Collecting pydantic~=1.10.6 (from nemoguardrails)
  Downloading pydantic-1.10.12-cp311-cp311-win_amd64.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 12.2 MB/s eta 0:00:00
Collecting aiohttp==3.8.4 (from nemoguardrails)
  Downloading aiohttp-3.8.4-cp311-cp311-win_amd64.whl (317 kB)
     ---------------------------------------- 317.2/317.2 kB 20.5 MB/s eta 0:00:00
Collecting langchain==0.0.167 (from nemoguardrails)
  Using cached langchain-0.0.167-py3-none-any.whl (809 kB)
Collecting requests>=2.31.0 (from nemoguardrails)
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting typer==0.7.0 (from nemoguardrails)
  Using cached typer-0.7.0-py3-none-any.whl (38 kB)
Requirement already satisfied: PyYAML~=6.0 in c:\users\archanadixit\anaconda3\lib\site-packages (from nemoguardrails) (6.0)
Collecting setuptools~=65.5.1 (from nemoguardrails)
  Using cached setuptools-65.5.1-py3-none-any.whl (1.2 MB)
Collecting annoy==1.17.1 (from nemoguardrails)
  Using cached annoy-1.17.1.tar.gz (647 kB)
  Preparing metadata (setup.py) ... done
Collecting sentence-transformers==2.2.2 (from nemoguardrails)
  Using cached sentence-transformers-2.2.2.tar.gz (85 kB)
  Preparing metadata (setup.py) ... done
Collecting fastapi==0.96.0 (from nemoguardrails)
  Using cached fastapi-0.96.0-py3-none-any.whl (57 kB)
Collecting starlette==0.27.0 (from nemoguardrails)
  Using cached starlette-0.27.0-py3-none-any.whl (66 kB)
Collecting uvicorn==0.22.0 (from nemoguardrails)
  Using cached uvicorn-0.22.0-py3-none-any.whl (58 kB)
Collecting httpx==0.23.3 (from nemoguardrails)
  Using cached httpx-0.23.3-py3-none-any.whl (71 kB)
Collecting simpleeval==0.9.13 (from nemoguardrails)
  Using cached simpleeval-0.9.13-py2.py3-none-any.whl (15 kB)
Collecting typing-extensions==4.5.0 (from nemoguardrails)
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Requirement already satisfied: Jinja2==3.1.2 in c:\users\archanadixit\anaconda3\lib\site-packages (from nemoguardrails) (3.1.2)
Requirement already satisfied: attrs>=17.3.0 in c:\users\archanadixit\anaconda3\lib\site-packages (from aiohttp==3.8.4->nemoguardrails) (22.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in c:\users\archanadixit\anaconda3\lib\site-packages (from aiohttp==3.8.4->nemoguardrails) (2.0.4)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\archanadixit\anaconda3\lib\site-packages (from aiohttp==3.8.4->nemoguardrails) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\archanadixit\anaconda3\lib\site-packages (from aiohttp==3.8.4->nemoguardrails) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\archanadixit\anaconda3\lib\site-packages (from aiohttp==3.8.4->nemoguardrails) (1.8.1)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\archanadixit\anaconda3\lib\site-packages (from aiohttp==3.8.4->nemoguardrails) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\archanadixit\anaconda3\lib\site-packages (from aiohttp==3.8.4->nemoguardrails) (1.2.0)
Requirement already satisfied: certifi in c:\users\archanadixit\anaconda3\lib\site-packages (from httpx==0.23.3->nemoguardrails) (2023.5.7)
Collecting httpcore<0.17.0,>=0.15.0 (from httpx==0.23.3->nemoguardrails)
  Using cached httpcore-0.16.3-py3-none-any.whl (69 kB)
Collecting rfc3986[idna2008]<2,>=1.3 (from httpx==0.23.3->nemoguardrails)
  Using cached rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Requirement already satisfied: sniffio in c:\users\archanadixit\anaconda3\lib\site-packages (from httpx==0.23.3->nemoguardrails) (1.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\archanadixit\anaconda3\lib\site-packages (from Jinja2==3.1.2->nemoguardrails) (2.1.1)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in c:\users\archanadixit\anaconda3\lib\site-packages (from langchain==0.0.167->nemoguardrails) (1.4.39)
Collecting dataclasses-json<0.6.0,>=0.5.7 (from langchain==0.0.167->nemoguardrails)
  Using cached dataclasses_json-0.5.13-py3-none-any.whl (26 kB)
Requirement already satisfied: numexpr<3.0.0,>=2.8.4 in c:\users\archanadixit\anaconda3\lib\site-packages (from langchain==0.0.167->nemoguardrails) (2.8.4)
Requirement already satisfied: numpy<2,>=1 in c:\users\archanadixit\anaconda3\lib\site-packages (from langchain==0.0.167->nemoguardrails) (1.24.3)
Collecting openapi-schema-pydantic<2.0,>=1.2 (from langchain==0.0.167->nemoguardrails)
  Using cached openapi_schema_pydantic-1.2.4-py3-none-any.whl (90 kB)
Requirement already satisfied: tenacity<9.0.0,>=8.1.0 in c:\users\archanadixit\anaconda3\lib\site-packages (from langchain==0.0.167->nemoguardrails) (8.2.2)
Requirement already satisfied: tqdm>=4.48.0 in c:\users\archanadixit\anaconda3\lib\site-packages (from langchain==0.0.167->nemoguardrails) (4.65.0)
Collecting transformers<5.0.0,>=4.6.0 (from sentence-transformers==2.2.2->nemoguardrails)
  Downloading transformers-4.31.0-py3-none-any.whl (7.4 MB)
     ---------------------------------------- 7.4/7.4 MB 14.8 MB/s eta 0:00:00
Collecting torch>=1.6.0 (from sentence-transformers==2.2.2->nemoguardrails)
  Downloading torch-2.0.1-cp311-cp311-win_amd64.whl (172.3 MB)
     ---------------------------------------- 172.3/172.3 MB 6.5 MB/s eta 0:00:00
Collecting torchvision (from sentence-transformers==2.2.2->nemoguardrails)
  Downloading torchvision-0.15.2-cp311-cp311-win_amd64.whl (1.2 MB)
     ---------------------------------------- 1.2/1.2 MB 4.2 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn in c:\users\archanadixit\anaconda3\lib\site-packages (from sentence-transformers==2.2.2->nemoguardrails) (1.2.2)
Requirement already satisfied: scipy in c:\users\archanadixit\anaconda3\lib\site-packages (from sentence-transformers==2.2.2->nemoguardrails) (1.10.1)
Requirement already satisfied: nltk in c:\users\archanadixit\anaconda3\lib\site-packages (from sentence-transformers==2.2.2->nemoguardrails) (3.7)
Collecting sentencepiece (from sentence-transformers==2.2.2->nemoguardrails)
  Downloading sentencepiece-0.1.99-cp311-cp311-win_amd64.whl (977 kB)
     ---------------------------------------- 977.5/977.5 kB 7.7 MB/s eta 0:00:00
Collecting huggingface-hub>=0.4.0 (from sentence-transformers==2.2.2->nemoguardrails)
  Using cached huggingface_hub-0.16.4-py3-none-any.whl (268 kB)
Requirement already satisfied: anyio<5,>=3.4.0 in c:\users\archanadixit\anaconda3\lib\site-packages (from starlette==0.27.0->nemoguardrails) (3.5.0)
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\users\archanadixit\anaconda3\lib\site-packages (from typer==0.7.0->nemoguardrails) (8.0.4)
Collecting h11>=0.8 (from uvicorn==0.22.0->nemoguardrails)
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Requirement already satisfied: idna<4,>=2.5 in c:\users\archanadixit\anaconda3\lib\site-packages (from requests>=2.31.0->nemoguardrails) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\archanadixit\anaconda3\lib\site-packages (from requests>=2.31.0->nemoguardrails) (1.26.16)
Requirement already satisfied: colorama in c:\users\archanadixit\anaconda3\lib\site-packages (from click<9.0.0,>=7.1.1->typer==0.7.0->nemoguardrails) (0.4.6)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.6.0,>=0.5.7->langchain==0.0.167->nemoguardrails)
  Using cached marshmallow-3.20.1-py3-none-any.whl (49 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.6.0,>=0.5.7->langchain==0.0.167->nemoguardrails)
  Using cached typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Requirement already satisfied: filelock in c:\users\archanadixit\anaconda3\lib\site-packages (from huggingface-hub>=0.4.0->sentence-transformers==2.2.2->nemoguardrails) (3.9.0)
Requirement already satisfied: fsspec in c:\users\archanadixit\anaconda3\lib\site-packages (from huggingface-hub>=0.4.0->sentence-transformers==2.2.2->nemoguardrails) (2023.3.0)
Requirement already satisfied: packaging>=20.9 in c:\users\archanadixit\anaconda3\lib\site-packages (from huggingface-hub>=0.4.0->sentence-transformers==2.2.2->nemoguardrails) (23.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\archanadixit\anaconda3\lib\site-packages (from SQLAlchemy<3,>=1.4->langchain==0.0.167->nemoguardrails) (2.0.1)
Requirement already satisfied: sympy in c:\users\archanadixit\anaconda3\lib\site-packages (from torch>=1.6.0->sentence-transformers==2.2.2->nemoguardrails) (1.11.1)
Requirement already satisfied: networkx in c:\users\archanadixit\anaconda3\lib\site-packages (from torch>=1.6.0->sentence-transformers==2.2.2->nemoguardrails) (2.8.4)
Requirement already satisfied: regex!=2019.12.17 in c:\users\archanadixit\anaconda3\lib\site-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers==2.2.2->nemoguardrails) (2022.7.9)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1 (from transformers<5.0.0,>=4.6.0->sentence-transformers==2.2.2->nemoguardrails)
  Downloading tokenizers-0.13.3-cp311-cp311-win_amd64.whl (3.5 MB)
     ---------------------------------------- 3.5/3.5 MB 7.6 MB/s eta 0:00:00
Collecting safetensors>=0.3.1 (from transformers<5.0.0,>=4.6.0->sentence-transformers==2.2.2->nemoguardrails)
  Downloading safetensors-0.3.1-cp311-cp311-win_amd64.whl (263 kB)
     ---------------------------------------- 263.7/263.7 kB 15.8 MB/s eta 0:00:00
Requirement already satisfied: joblib in c:\users\archanadixit\anaconda3\lib\site-packages (from nltk->sentence-transformers==2.2.2->nemoguardrails) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\archanadixit\anaconda3\lib\site-packages (from scikit-learn->sentence-transformers==2.2.2->nemoguardrails) (2.2.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\archanadixit\anaconda3\lib\site-packages (from torchvision->sentence-transformers==2.2.2->nemoguardrails) (9.4.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\archanadixit\anaconda3\lib\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.6.0,>=0.5.7->langchain==0.0.167->nemoguardrails) (0.4.3)
Requirement already satisfied: mpmath>=0.19 in c:\users\archanadixit\anaconda3\lib\site-packages (from sympy->torch>=1.6.0->sentence-transformers==2.2.2->nemoguardrails) (1.2.1)
Building wheels for collected packages: annoy, sentence-transformers
  Building wheel for annoy (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      C:\Users\ArchanaDixit\anaconda3\Lib\site-packages\setuptools\__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\annoy
      copying annoy\__init__.py -> build\lib.win-amd64-cpython-311\annoy
      copying annoy\__init__.pyi -> build\lib.win-amd64-cpython-311\annoy
      copying annoy\py.typed -> build\lib.win-amd64-cpython-311\annoy
      running build_ext
      building 'annoy.annoylib' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for annoy
  Running setup.py clean for annoy
  Building wheel for sentence-transformers (setup.py) ... done
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125960 sha256=2edcca3561e70321af43ae689d0e6a66608d6657bfba4b64130a109a0a80f48d
  Stored in directory: c:\users\archanadixit\appdata\local\pip\cache\wheels\ff\27\bf\ffba8b318b02d7f691a57084ee154e26ed24d012b0c7805881
Successfully built sentence-transformers
Failed to build annoy
ERROR: Could not build wheels for annoy, which is required to install pyproject.toml-based projects
"""

**Comment by oscarnz** [comment]
I have the same error running on bitbucket pipelines, any solution on these?

**Comment by trebedea** [comment]
Hi @archanadixit ,

Thanks for signaling this.
We had not testing an install on Windows 64 bit with python 3.11 until now. But I have just installed the latest release (`nemoguardrails-0.4.0`) today on a fresh venv with 3.11 and did not encounter any issues (log is below). 

As far as I understand, your problem is related to not having installed Microsoft C++ Build Tools on your machine

_building 'annoy.annoylib' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/_

Can you check if this is the case and install the build tools if you don't have them? 
If this solves your problem, please close the issue. 

My clean install log:

_(venv) C:\Users\trebedea\projects\test-python-3.11>pip install nemoguardrails
Collecting nemoguardrails
  Downloading nemoguardrails-0.4.0-py3-none-any.whl (13.9 MB)
     ---------------------------------------- 13.9/13.9 MB 1.1 MB/s eta 0:00:00
Collecting pydantic~=1.10.6
  Downloading pydantic-1.10.12-cp311-cp311-win_amd64.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 555.5 kB/s eta 0:00:00
Collecting aiohttp==3.8.4
  Downloading aiohttp-3.8.4-cp311-cp311-win_amd64.whl (317 kB)
     ---------------------------------------- 317.2/317.2 kB 561.2 kB/s eta 0:00:00
Collecting langchain==0.0.251
  Using cached langchain-0.0.251-py3-none-any.whl (1.4 MB)
Collecting requests>=2.31.0
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting typer==0.7.0
  Using cached typer-0.7.0-py3-none-any.whl (38 kB)
Collecting PyYAML~=6.0
  Downloading PyYAML-6.0.1-cp311-cp311-win_amd64.whl (144 kB)
     ---------------------------------------- 144.7/144.7 kB 537.8 kB/s eta 0:00:00
Collecting setuptools~=65.5.1
  Using cached setuptools-65.5.1-py3-none-any.whl (1.2 MB)
Collecting annoy==1.17.3
  Using cached annoy-1.17.3.tar.gz (647 kB)
  Preparing metadata (setup.py) ... done
Collecting sentence-transformers==2.2.2
  Using cached sentence-transformers-2.2.2.tar.gz (85 kB)
  Preparing metadata (setup.py) ... done
Collecting fastapi==0.96.0
  Using cached fastapi-0.96.0-py3-none-any.whl (57 kB)
Collecting starlette==0.27.0
  Using cached starlette-0.27.0-py3-none-any.whl (66 kB)
Collecting uvicorn==0.22.0
  Using cached uvicorn-0.22.0-py3-none-any.whl (58 kB)
Collecting httpx==0.23.3
  Using cached httpx-0.23.3-py3-none-any.whl (71 kB)
Collecting simpleeval==0.9.13
  Using cached simpleeval-0.9.13-py2.py3-none-any.whl (15 kB)
Collecting typing-extensions==4.5.0
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting Jinja2==3.1.2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting attrs>=17.3.0
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting charset-normalizer<4.0,>=2.0
  Downloading charset_normalizer-3.2.0-cp311-cp311-win_amd64.whl (96 kB)
     ---------------------------------------- 96.6/96.6 kB 690.5 kB/s eta 0:00:00
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.4-cp311-cp311-win_amd64.whl (28 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.9.2-cp311-cp311-win_amd64.whl (60 kB)
     ---------------------------------------- 60.2/60.2 kB 640.7 kB/s eta 0:00:00
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.4.0-cp311-cp311-win_amd64.whl (44 kB)
     ---------------------------------------- 44.9/44.9 kB 550.6 kB/s eta 0:00:00
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting certifi
  Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Collecting httpcore<0.17.0,>=0.15.0
  Using cached httpcore-0.16.3-py3-none-any.whl (69 kB)
Collecting rfc3986[idna2008]<2,>=1.3
  Using cached rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Collecting sniffio
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.3-cp311-cp311-win_amd64.whl (17 kB)
Collecting SQLAlchemy<3,>=1.4
  Downloading SQLAlchemy-2.0.19-cp311-cp311-win_amd64.whl (2.0 MB)
     ---------------------------------------- 2.0/2.0 MB 567.6 kB/s eta 0:00:00
Collecting dataclasses-json<0.6.0,>=0.5.7
  Downloading dataclasses_json-0.5.14-py3-none-any.whl (26 kB)
Collecting langsmith<0.1.0,>=0.0.11
  Downloading langsmith-0.0.22-py3-none-any.whl (32 kB)
Collecting numexpr<3.0.0,>=2.8.4
  Downloading numexpr-2.8.5-cp311-cp311-win_amd64.whl (94 kB)
     ---------------------------------------- 94.4/94.4 kB 771.9 kB/s eta 0:00:00
Collecting numpy<2,>=1
  Downloading numpy-1.25.2-cp311-cp311-win_amd64.whl (15.5 MB)
     ---------------------------------------- 15.5/15.5 MB 3.0 MB/s eta 0:00:00
Collecting openapi-schema-pydantic<2.0,>=1.2
  Using cached openapi_schema_pydantic-1.2.4-py3-none-any.whl (90 kB)
Collecting tenacity<9.0.0,>=8.1.0
  Downloading tenacity-8.2.3-py3-none-any.whl (24 kB)
Collecting transformers<5.0.0,>=4.6.0
  Using cached transformers-4.31.0-py3-none-any.whl (7.4 MB)
Collecting tqdm
  Downloading tqdm-4.66.1-py3-none-any.whl (78 kB)
     ---------------------------------------- 78.3/78.3 kB 4.3 MB/s eta 0:00:00
Collecting torch>=1.6.0
  Downloading torch-2.0.1-cp311-cp311-win_amd64.whl (172.3 MB)
     ---------------------------------------- 172.3/172.3 MB 9.8 MB/s eta 0:00:00
Collecting torchvision
  Downloading torchvision-0.15.2-cp311-cp311-win_amd64.whl (1.2 MB)
     ---------------------------------------- 1.2/1.2 MB 304.7 kB/s eta 0:00:00
Collecting scikit-learn
  Downloading scikit_learn-1.3.0-cp311-cp311-win_amd64.whl (9.2 MB)
     ---------------------------------------- 9.2/9.2 MB 13.7 MB/s eta 0:00:00
Collecting scipy
  Downloading scipy-1.11.1-cp311-cp311-win_amd64.whl (44.0 MB)
     ---------------------------------------- 44.0/44.0 MB 13.4 MB/s eta 0:00:00
Collecting nltk
  Using cached nltk-3.8.1-py3-none-any.whl (1.5 MB)
Collecting sentencepiece
  Downloading sentencepiece-0.1.99-cp311-cp311-win_amd64.whl (977 kB)
     ---------------------------------------- 977.5/977.5 kB 12.4 MB/s eta 0:00:00
Collecting huggingface-hub>=0.4.0
  Using cached huggingface_hub-0.16.4-py3-none-any.whl (268 kB)
Collecting anyio<5,>=3.4.0
  Using cached anyio-3.7.1-py3-none-any.whl (80 kB)
Collecting click<9.0.0,>=7.1.1
  Using cached click-8.1.6-py3-none-any.whl (97 kB)
Collecting h11>=0.8
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.0.4-py3-none-any.whl (123 kB)
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting marshmallow<4.0.0,>=3.18.0
  Using cached marshmallow-3.20.1-py3-none-any.whl (49 kB)
Collecting typing-inspect<1,>=0.4.0
  Using cached typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Collecting filelock
  Using cached filelock-3.12.2-py3-none-any.whl (10 kB)
Collecting fsspec
  Using cached fsspec-2023.6.0-py3-none-any.whl (163 kB)
Collecting packaging>=20.9
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting greenlet!=0.4.17
  Downloading greenlet-2.0.2-cp311-cp311-win_amd64.whl (192 kB)
     ---------------------------------------- 192.5/192.5 kB 12.1 MB/s eta 0:00:00
Collecting sympy
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting networkx
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting regex!=2019.12.17
  Downloading regex-2023.8.8-cp311-cp311-win_amd64.whl (268 kB)
     ---------------------------------------- 268.3/268.3 kB 8.1 MB/s eta 0:00:00
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1
  Downloading tokenizers-0.13.3-cp311-cp311-win_amd64.whl (3.5 MB)
     ---------------------------------------- 3.5/3.5 MB 14.8 MB/s eta 0:00:00
Collecting safetensors>=0.3.1
  Downloading safetensors-0.3.2-cp311-cp311-win_amd64.whl (266 kB)
     ---------------------------------------- 266.3/266.3 kB 17.1 MB/s eta 0:00:00
Collecting joblib
  Downloading joblib-1.3.2-py3-none-any.whl (302 kB)
     ---------------------------------------- 302.2/302.2 kB 19.5 MB/s eta 0:00:00
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.2.0-py3-none-any.whl (15 kB)
Collecting pillow!=8.3.*,>=5.3.0
  Downloading Pillow-10.0.0-cp311-cp311-win_amd64.whl (2.5 MB)
     ---------------------------------------- 2.5/2.5 MB 17.8 MB/s eta 0:00:00
Collecting mypy-extensions>=0.3.0
  Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Building wheels for collected packages: annoy, sentence-transformers
  Building wheel for annoy (setup.py) ... done
  Created wheel for annoy: filename=annoy-1.17.3-cp311-cp311-win_amd64.whl size=52210 sha256=58bb4db45af8b00cd8eb1f3bb07c5abc4105a46fba9855c576c6fcbaa1c6a5b9
  Stored in directory: c:\users\trebedea\appdata\local\pip\cache\wheels\6f\b7\de\ac2140ac002f1205a2585937fa08a096ad3f23a8a7dd4b0976
  Building wheel for sentence-transformers (setup.py) ... done
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125960 sha256=ebb3a4e904fe795e0b5b02fe5b4522ac5147f68057a38520650fd8d81e958715
  Stored in directory: c:\users\trebedea\appdata\local\pip\cache\wheels\c5\ca\33\8657d5aded943d57e56bf40ec332c8960f9f3f70a143e34731
Successfully built annoy sentence-transformers
Installing collected packages: tokenizers, simpleeval, sentencepiece, safetensors, rfc3986, mpmath, annoy, urllib3, typing-extensions, threadpoolctl, tenacity, sympy, sniffio, setuptools, regex, PyYAML, pillow, packaging, numpy, networkx, mypy-extensions, multidict, MarkupSafe, joblib, idna, h11, greenlet, fsspec, frozenlist, filelock, colorama, charset-normalizer, certifi, attrs, async-timeout, yarl, typing-inspect, tqdm, SQLAlchemy, scipy, requests, pydantic, numexpr, marshmallow, Jinja2, click, anyio, aiosignal, uvicorn, typer, torch, starlette, scikit-learn, openapi-schema-pydantic, nltk, langsmith, huggingface-hub, httpcore, dataclasses-json, aiohttp, transformers, torchvision, langchain, httpx, fastapi, sentence-transformers, nemoguardrails
  Attempting uninstall: setuptools
    Found existing installation: setuptools 65.6.3
    Uninstalling setuptools-65.6.3:
      Successfully uninstalled setuptools-65.6.3
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.3 PyYAML-6.0.1 SQLAlchemy-2.0.19 aiohttp-3.8.4 aiosignal-1.3.1 annoy-1.17.3 anyio-3.7.1 async-timeout-4.0.3 attrs-23.1.0 certifi-2023.7.22 charset-normalizer-3.2.0 click-8.1.6 colorama-0.4.6 dataclasses-json-0.5.14 fastapi-0.96.0 filelock-3.12.2 frozenlist-1.4.0 fsspec-2023.6.0 greenlet-2.0.2 h11-0.14.0 httpcore-0.16.3 httpx-0.23.3 huggingface-hub-0.16.4 idna-3.4 joblib-1.3.2 langchain-0.0.251 langsmith-0.0.22 marshmallow-3.20.1 mpmath-1.3.0 multidict-6.0.4 mypy-extensions-1.0.0 nemoguardrails-0.4.0 networkx-3.1 nltk-3.8.1 numexpr-2.8.5 numpy-1.25.2 openapi-schema-pydantic-1.2.4 packaging-23.1 pillow-10.0.0 pydantic-1.10.12 regex-2023.8.8 requests-2.31.0 rfc3986-1.5.0 safetensors-0.3.2 scikit-learn-1.3.0 scipy-1.11.1 sentence-transformers-2.2.2 sentencepiece-0.1.99 setuptools-65.5.1 simpleeval-0.9.13 sniffio-1.3.0 starlette-0.27.0 sympy-1.12 tenacity-8.2.3 threadpoolctl-3.2.0 tokenizers-0.13.3 torch-2.0.1 torchvision-0.15.2 tqdm-4.66.1 transformers-4.31.0 typer-0.7.0 typing-extensions-4.5.0 typing-inspect-0.9.0 urllib3-2.0.4 uvicorn-0.22.0 yarl-1.9.2_

**Comment by archanadixit** [comment]
Hi @trebedea 

Apologies for late response. 
I will close this issue for now.

-Archana
